### ISSUE TITLE
Drop nrwl for nx as prefix

### ISSUE THREAD

**Issue by JonasLuechau** [altack/nx-bundlefy#1]
With NX 16 the prefix nrwl got dropped, to be compatible with it the executor needs following changes:

```
const devkit_1 = require("@nx/devkit");
const fileutils_1 = require("@nx/workspace/src/utils/fileutils");
const buildable_libs_utils_1 = require("@nx/js/src/utils/buildable-libs-utils");
```

At least for me that fixed things, otherwise I get the error `Cannot find module '@nrwl/workspace/src/utils/fileutils'`.

**Comment by wall-street-dev** [comment]
Right... expect a new release by the end of this week

**Comment by wall-street-dev** [comment]
Alright, v0.16.0 published: https://www.npmjs.com/package/@altack/nx-bundlefy
