### ISSUE TITLE
Support for nx 16

### ISSUE THREAD

**Issue by andyg3** [altack/nx-bundlefy#6]
EDIT: I just saw that you made some commits for NX16. Can that please be published to npm?

I am using nx 16 and was able to make some progress with v0.15.0, with one change:

Changed the `require`s in `index.js` from `@nrwl` to `@nx`

However, I receive the error `Cannot read properties of undefined (reading 'options')`

Can you add support for nx 16 or provide a workaround for this missing property?

**Comment by wall-street-dev** [comment]
Hi @andyg3, just use the v16 `npm i @altack/nx-bundlefy@0.16.0`

**Comment by andyg3** [comment]
Oh, duh. I was too lazy to notice it was already released. Thanks!
